### ISSUE TITLE
Error regarding search config: Search plugin ConfigValidationError: provider is a required field

### ISSUE THREAD

**Issue by YehorSivachenko** [MattieBelt/mattie-strapi-bundle#127]
Hi!
I have an issue that looks like this:
`error: Error regarding search config: Search plugin ConfigValidationError: provider is a required field
Error: Error regarding search config: Search plugin ConfigValidationError: provider is a required field
     at applyUserConfig (/app/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:72:13)
     at async Object.loadPlugins (/app/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:100:3)
     at async Strapi.loadPlugins (/app/node_modules/@strapi/strapi/lib/Strapi.js:333:5)
     at async Promise.all (index 2)
     at async Strapi.register (/app/node_modules/@strapi/strapi/lib/Strapi.js:369:5)
     at async Strapi.load (/app/node_modules/@strapi/strapi/lib/Strapi.js:474:5)
     at async Strapi.start (/app/node_modules/@strapi/strapi/lib/Strapi.js:212:9)
 error Command failed with exit code 1.
 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
 
 But I have basic plugin setup and provider in it:
 `search: {
            enabled: true,
            config: {
              provider: 'algolia',
              providerOptions: {
                apiKey: env('ALGOLIA_PROVIDER_ADMIN_API_KEY'),
                applicationId: env('ALGOLIA_PROVIDER_APPLICATION_ID'),
              },
              contentTypes: [
                { name: 'api::article.article' },
                { name: 'api::category.category' },
              ],
            },
          },`
          
          How is it possible to fix it? Additionally I use node 18 maybe that's the reason?

**Comment by Florian-crg** [comment]
Same error here. The only thing I did is following the https://mattie-bundle.mattiebelt.com/quick-start ...
Using node v16.17.0

**Comment by Florian-crg** [comment]
To fix the issue run `yarn build`

**Comment by YehorSivachenko** [comment]
my mistake, the config was not included for development
